### ISSUE TITLE
Working on hyperopt.py 

### ISSUE THREAD

**Issue by bluzeey** [arita37/dsa2#112]
Hey there arita37 , I have opened this issue to contribute towards working on hyperoptimization function in hyperopt.py

**Comment by bluzeey** [comment]
I tried to use the function run_hyperoptuna , and as I understand , objective function should be the metric with model trained which we want to minimize, parse_dict  seems to be the range of parameters which we will use to optimize the function , however I seem not understand engine_pars(engine parameters functions). Any elaboration on the same , would be greatly appreciated , looking forward to hearing from you!

**Comment by arita37** [comment]
engine_pars : optuna specific param,
like ntrials, database name,...
