### ISSUE TITLE
Time series classification problem

### ISSUE THREAD

**Issue by raihan19** [arita37/dsa2#168]
Hi, I have been told to implement the code ([https://github.com/arita37/dsa2/blob/main/titanic_classifier.py](url)) on any of the time series datasets which can be found here: [https://archive.ics.uci.edu/ml/index.php](url). So, to do this, I have chosen the following dataset: [https://archive.ics.uci.edu/ml/datasets/selfBACK](url). From this dataset, I have considered two opposite activity classes (upstairs and downstairs) and only took the first 20 instances from each user and put them into one file. Then, followed the instruction mentioned here: [https://github.com/arita37/dsa2](url) and [https://github.com/arita37/dsa2/issues/121](url). However, I am still getting the following error:
`ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg`

To resolve this issue, I tried to eliminate duplicate rows and I found there is none of them. After that, I edited `util_feature.py` which is a built-in library where I changed the code from `df[cbin] = pd.cut(df[c], bins=lbins, labels=labels)` to this `df[cbin] = pd.cut(df[c], bins=lbins, labels=labels, duplicates='drop')`. This generates a new error: `ValueError: Bin labels must be one fewer than the number of bin edges`. I tried the recommended solution found here: [https://stackoverflow.com/questions/20158597/how-to-qcut-with-non-unique-bin-edges/40548606#40548606](url). But nothing seems to work.

Any suggestion will be much appreciated. My code and data file can be found here: [https://drive.google.com/drive/folders/1tjkHJoLfLHWIC_qLQs0T1_Bp1Y0EzNYO?usp=sharing](url).

**Comment by arita37** [comment]
Why na values everywhere ?
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]).

**Comment by raihan19** [comment]
> Why na values everywhere ?
> array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]).

I am not sure.
